apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grafana
data:
  datasource.yaml: |
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        #If prometheus server is setup on same cluster, use Kubernetes service discovery
        #If prometheus server is on another cluster, user GCP Internal Loadbalancer to avoid exposing service to public
        url: http://prometheus-server:80
  
