{{- if .Values.global.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-conf
  namespace: {{ .Values.global.namespace }}
  labels:
    app: grafana
data:
  #Define grafana configuration here
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    #Path where grafana PVC is mounted for persistence
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
{{- end -}}

