{{- if .Values.global.jvm.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appspec.name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    prometheus.io/scrape: "true"  #Required annotation to configure service for prometheus scraping
    prometheus.io/port: "8080"    #Define port and path here. Defaults to /metrics path.
  labels:
    app: {{ .Values.appspec.name }}
spec:
  selector: 
    app: {{ .Values.appspec.name }}
  type: {{ .Values.service.type }}  
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      name: http
      protocol: TCP
{{- end -}}
