#Manage your prometheus service configurations here
{{- if .Values.global.prometheus.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appspec.name }}-{{ .Values.appspec.component }}
  namespace: {{ .Values.global.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
      cloud.google.com/load-balancer-type: "Internal"
spec:
  selector: 
    app: {{ .Values.appspec.name }}
    component: {{ .Values.appspec.component }}
  type: {{ .Values.service.type }}  
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      name: http
      protocol: TCP
{{- end -}}
